title: Voidhead Studios
description: >- 
  We're a new indie studio based out of Nottingham, UK.
lang: en-GB
permalink: pretty

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

remote_theme: jonaharagon/jekyll-bootstrap-theme

# Social
email: team@voidheadstudios.com
